let data = [
  {
    firstName: "Adamu",
    lastName: "Muhammad",
    year: "2006",
    email: "adamu.dankore@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580212587162",
    nickname: "Samdanko",
    residence: "Iowa",
    class: "SS3A",
    occupation: "Software Engineer",
    teacher: "Mr. Wellington Oboh",
    month: "July",
    day: "02",
    phone: "+13192965799",
    social_type_1: "Twitter",
    link_social_type_1: "https://twitter.com/adamuMdankore",
    social_type_2: "Facebook",
    link_social_type_2: "https://www.facebook.com/adamu.muhammad.dankore",
    relationship: "Married"
  },
  {
    firstName: "Fatima",
    lastName: "Usman",
    year: "2008",
    email: "usmanfatima61@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580491991787",
    nickname: "",
    residence: "",
    class: "SS3A",
    occupation: "",
    teacher: "",
    month: "December",
    day: "30",
    phone: "",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: undefined
  },
  {
    firstName: "Nurudeen",
    lastName: "Audu",
    year: "2006",
    email: "Prolificnuru@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580504019570",
    nickname: "Fabulous",
    residence: "Brick city estate Kubwa",
    class: "SS3E",
    occupation: "Tax Consultant, Civil servant and Videographer",
    teacher: "Wellington",
    month: "December",
    day: "14",
    phone: "08039162233",
    social_type_1: "Twitter",
    link_social_type_1: "https://twitter.com/elfab?s=08",
    social_type_2: "Facebook",
    link_social_type_2: "https://www.facebook.com/fabulous.nuru",
    relationship: undefined
  },
  {
    firstName: "ADEOYE",
    lastName: "JOHN",
    year: "2006",
    email: "johnadeoye55@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580503409242",
    nickname: "vandarsa",
    residence: "",
    class: "",
    occupation: "",
    teacher: "",
    month: "",
    day: "",
    phone: "",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: undefined
  },
  {
    firstName: "Suleiman",
    lastName: "UmarFaruk",
    year: "2008",
    email: "Yabaagi@gmail.com",
    photo: "",
    nickname: "",
    residence: "",
    class: "",
    occupation: "",
    teacher: "",
    month: "",
    day: "",
    phone: "",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: undefined
  },
  {
    firstName: "Collins",
    lastName: "Asogwa",
    year: "2006",
    email: "eunoch@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580506011094",
    nickname: "",
    residence: "Abuja, Nigeria ",
    class: "SS3F",
    occupation: "Theatre and Media Consultant ",
    teacher: "Miss Nnenna Orji (Literature in English) ",
    month: "September",
    day: "6",
    phone: "+2348066403478",
    social_type_1: "Facebook",
    link_social_type_1: "https://www.facebook.com/AsogwaPikin",
    social_type_2: "Twitter",
    link_social_type_2: "https://twitter.com/Septmeniac",
    relationship: undefined
  },
  {
    firstName: "Ahmed",
    lastName: "Abdullahi",
    year: "2006",
    email: "ahmedjibrin6@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580504838127",
    nickname: "",
    residence: "Bida",
    class: "SS3F",
    occupation: "Assistant lecturer Federal polytechnic bid",
    teacher: "",
    month: "October",
    day: "19",
    phone: "08032576849",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: undefined
  },
  {
    firstName: "Victor",
    lastName: "Ezenwa",
    year: "2006",
    email: "thetutor4@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580508390094",
    nickname: "Skyklash",
    residence: "Lugbe, Abuja ",
    class: "SS3C",
    occupation: "Project Manager ",
    teacher: "",
    month: "February",
    day: "19",
    phone: "08062686193",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: undefined
  },
  {
    firstName: "Usman",
    lastName: "Gimba",
    year: "2006",
    email: "Gimbausmanndako@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580507524089",
    nickname: "Gimba",
    residence: "Kubwa",
    class: "SS3F",
    occupation: "",
    teacher: "",
    month: "June",
    day: "18",
    phone: "08162539303",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: undefined
  },
  {
    firstName: "Manasseh",
    lastName: "Joseph",
    year: "2006",
    email: "ezhanasss@gmail.com",
    photo: "",
    nickname: undefined,
    residence: undefined,
    class: undefined,
    occupation: undefined,
    teacher: undefined,
    month: undefined,
    day: undefined,
    phone: undefined,
    social_type_1: undefined,
    link_social_type_1: undefined,
    social_type_2: undefined,
    link_social_type_2: undefined,
    relationship: undefined
  },
  {
    firstName: "Imoh",
    lastName: "Etebom",
    year: "2006",
    email: "lilyblackdiamond@gmail.com",
    photo: "",
    nickname: "Black Diamond ",
    residence: "Chika Along Airport Road",
    class: "SS3F",
    occupation: "Realtor",
    teacher: "",
    month: "June",
    day: "27",
    phone: "08076063485",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: undefined
  },
  {
    firstName: "Oni",
    lastName: "JOHNVESSEL",
    year: "2006",
    email: "vesseljohnwithcare@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580508731398",
    nickname: "",
    residence: "Kaduna, Nigeria",
    class: "SS3F",
    occupation: "",
    teacher: "Miss Ayo",
    month: "June",
    day: "13",
    phone: "",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: undefined
  },
  {
    firstName: "Emeka",
    lastName: "Ejike",
    year: "2006",
    email: "emekaejike203@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580510160405",
    nickname: "Mecxy the Tallest",
    residence: "Maiduguri",
    class: "SS3B",
    occupation: "Construction Engineer",
    teacher: "",
    month: "",
    day: "",
    phone: "08030444203",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: undefined
  },
  {
    firstName: "ojo",
    lastName: "samuel",
    year: "2006",
    email: "olaniyisamojo@yahoo.com",
    photo: "",
    nickname: undefined,
    residence: undefined,
    class: undefined,
    occupation: undefined,
    teacher: undefined,
    month: undefined,
    day: undefined,
    phone: undefined,
    social_type_1: undefined,
    link_social_type_1: undefined,
    social_type_2: undefined,
    link_social_type_2: undefined,
    relationship: undefined
  },
  {
    firstName: "ANYAEZE",
    lastName: "STANLEY",
    year: "2006",
    email: "exleysanyaeze@gmail.com",
    photo: "",
    nickname: "",
    residence: "",
    class: "",
    occupation: "",
    teacher: "",
    month: "",
    day: "",
    phone: "",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: ""
  },
  {
    firstName: "Emmanuel",
    lastName: "Okoro",
    year: "2006",
    email: "ecokoro2@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580539155012",
    nickname: "Emma",
    residence: "Wisconsin",
    class: "SS3A",
    occupation: "GIS Developer/Data Analyst",
    teacher: "Mr Vincent - Maths and Mrs Okonkwo - Biology",
    month: "June",
    day: "10",
    phone: "+14144003392",
    social_type_1: "Facebook",
    link_social_type_1: "https://www.facebook.com/sample.emmanuel",
    social_type_2: "Instagram",
    link_social_type_2: "https://www.instagram.com/sample_naira/",
    relationship: ""
  },
  {
    firstName: "Njoku",
    lastName: "Friday",
    year: "2010",
    email: "emmymich56@gmail.com",
    photo: "",
    nickname: undefined,
    residence: undefined,
    class: undefined,
    occupation: undefined,
    teacher: undefined,
    month: undefined,
    day: undefined,
    phone: undefined,
    social_type_1: undefined,
    link_social_type_1: undefined,
    social_type_2: undefined,
    link_social_type_2: undefined,
    relationship: undefined
  },
  {
    firstName: "Chisom",
    lastName: "Izuogu",
    year: "2008",
    email: "xtrabright001@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580547129914",
    nickname: "Sommy",
    residence: "Asokoro, Abuja",
    class: "SS3C",
    occupation: "Business Analyst",
    teacher: "",
    month: "November",
    day: "11",
    phone: "",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: "Married"
  },
  {
    firstName: "Isah",
    lastName: "Bello",
    year: "2006",
    email: "bellosaidu84@gmail.com",
    photo: "",
    nickname: "Ayatul ",
    residence: "Abuja Nigerian",
    class: "2006",
    occupation: "",
    teacher: "",
    month: "",
    day: "",
    phone: "7065058475",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: ""
  },
  {
    firstName: "Wisdom",
    lastName: "Koko",
    year: "2006",
    email: "wisdomfelix6@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580559222115",
    nickname: "Wizzy",
    residence: "IKEJA",
    class: "",
    occupation: "NETWORK MARKETING ",
    teacher: "",
    month: "December",
    day: "21",
    phone: "",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: ""
  },
  {
    firstName: "ERNEST",
    lastName: "UKA",
    year: "2006",
    email: "ukaernest.ekene@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580583044348",
    nickname: "Champion",
    residence: "Owerri",
    class: "SS3E",
    occupation: "",
    teacher: "",
    month: "June",
    day: "30",
    phone: "07033648823",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: ""
  },
  {
    firstName: "Silas",
    lastName: "Zugumnaan",
    year: "2016",
    email: "zugumnan@ahoo.com",
    photo: "",
    nickname: undefined,
    residence: undefined,
    class: undefined,
    occupation: undefined,
    teacher: undefined,
    month: undefined,
    day: undefined,
    phone: undefined,
    social_type_1: undefined,
    link_social_type_1: undefined,
    social_type_2: undefined,
    link_social_type_2: undefined,
    relationship: undefined
  },
  {
    firstName: "SUNDAY",
    lastName: "OKOH",
    year: "2004",
    email: "sundaycosmas104@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580585257999",
    nickname: "",
    residence: "KUJE ABUJA",
    class: "SS3",
    occupation: "ASM The LaCasera Company Plc",
    teacher: "",
    month: "November",
    day: "24",
    phone: "07033165462",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: "Married"
  },
  {
    firstName: "Fatai",
    lastName: "Saheed",
    year: "2007",
    email: "Fataisaheedayobami95@gmail.com",
    photo: "",
    nickname: undefined,
    residence: undefined,
    class: undefined,
    occupation: undefined,
    teacher: undefined,
    month: undefined,
    day: undefined,
    phone: undefined,
    social_type_1: undefined,
    link_social_type_1: undefined,
    social_type_2: undefined,
    link_social_type_2: undefined,
    relationship: undefined
  },
  {
    firstName: "Ahmed",
    lastName: "Adegboye",
    year: "2007",
    email: "ahmedmedy144@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580619180555",
    nickname: "Medo",
    residence: "Maiduguri",
    class: "SS3E",
    occupation: "Procurement",
    teacher: "Mr Wilington",
    month: "April",
    day: "23",
    phone: "8162426206",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: "Single"
  },
  {
    firstName: "Onukwugha",
    lastName: "Franklyn",
    year: "2005",
    email: "elechidi@hotmail.com",
    photo: "",
    nickname: undefined,
    residence: undefined,
    class: undefined,
    occupation: undefined,
    teacher: undefined,
    month: undefined,
    day: undefined,
    phone: undefined,
    social_type_1: undefined,
    link_social_type_1: undefined,
    social_type_2: undefined,
    link_social_type_2: undefined,
    relationship: undefined
  },
  {
    firstName: "Alex",
    lastName: "Idolor",
    year: "2007",
    email: "frowish@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580621580440",
    nickname: "Frowish",
    residence: "Abuja",
    class: "SS3C",
    occupation: "",
    teacher: "",
    month: "April",
    day: "28",
    phone: "",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: "Single"
  },
  {
    firstName: "JULIANA",
    lastName: "ABRAHAM",
    year: "2005",
    email: "leelee4mumccy@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580629627915",
    nickname: "",
    residence: "Abuja",
    class: "",
    occupation: "",
    teacher: "",
    month: "",
    day: "",
    phone: "",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: ""
  },
  {
    firstName: "Moses",
    lastName: "Adejola",
    year: "2007",
    email: "Adejolamoses9@gmail.com",
    photo: "",
    nickname: undefined,
    residence: undefined,
    class: undefined,
    occupation: undefined,
    teacher: undefined,
    month: undefined,
    day: undefined,
    phone: undefined,
    social_type_1: undefined,
    link_social_type_1: undefined,
    social_type_2: undefined,
    link_social_type_2: undefined,
    relationship: undefined
  },
  {
    firstName: "Adeyemo",
    lastName: "Abdulrazaq",
    year: "2007",
    email: "gentledude65@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580652985987",
    nickname: "",
    residence: "Otta, ogun state",
    class: "2007",
    occupation: "",
    teacher: "",
    month: "April",
    day: "27",
    phone: "",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: ""
  },
  {
    firstName: "Emmanuel",
    lastName: "Odey",
    year: "2007",
    email: "nelsonnewton15@gmail.com",
    photo: "",
    nickname: "Emmy Ratty",
    residence: "Abuja",
    class: "SS3a",
    occupation: "Chef",
    teacher: "",
    month: "November",
    day: "23",
    phone: "08067758046",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: "Married"
  },
  {
    firstName: "Oluebubechi",
    lastName: "Ogu",
    year: "2005",
    email: "Princedubem428@gmail.com",
    photo: "",
    nickname: undefined,
    residence: undefined,
    class: undefined,
    occupation: undefined,
    teacher: undefined,
    month: undefined,
    day: undefined,
    phone: undefined,
    social_type_1: undefined,
    link_social_type_1: undefined,
    social_type_2: undefined,
    link_social_type_2: undefined,
    relationship: undefined
  },
  {
    firstName: "Jude",
    lastName: "Nwachukwu",
    year: "2007",
    email: "nwachukwujude@gmail.com",
    photo: "https://gss-gwarinpa.s3.us-east-2.amazonaws.com/1580691690173",
    nickname: "Smart j",
    residence: "Belfast",
    class: "2006",
    occupation: "Hospitality management ",
    teacher: "",
    month: "June",
    day: "3",
    phone: "",
    social_type_1: "",
    link_social_type_1: "",
    social_type_2: "",
    link_social_type_2: "",
    relationship: "Married"
  }
];
let profile = "olaniyisamojo@yahoo.com";
let emails = [
  // { color: "no", profileEmail: "emekaejike203@gmail.com" },
  // { color: "no", profileEmail: "olaniyisamojo@yahoo.com" },
  // { color: "yes", profileEmail: "Olivechords@gmail.com" },
  // { color: "yes", profileEmail: "ajtopsy01@gmail.com" }
];


// let g = emails.map(item => {

//   if(item.profileEmail == profile){
//     return item.color
//   }
// }).filter(Boolean)
let g = ""
for(var i = 0; i < emails.length; i++){
  
  if(emails[i].profileEmail == profile){
    console.log(emails[i]);
    g = emails[i].color
  }
}

console.log(g)


    